branches = [ "master", "develop" ]
author_emails = [ "gubasso@eambar.net", "gubasso@cwnt.io" ]

[[hosts]]
host = "Gitlab"
user = "gubasso"

[[hosts]]
host = "github"
user = "gubasso"

[[hosts]]
host = "github"
user = "cwnt-io"
