services:
  db:
    image: "postgres:${POSTGRES_VERSION}"
    restart: always
    volumes:
      - ${DATA_PATH}:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    healthcheck:
      test: psql -U ${POSTGRES_USER} -q -d ${POSTGRES_DB} -c "SELECT 'ready';"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    secrets:
      - postgres_password
secrets:
  postgres_password:
    environment: "POSTGRES_PASSWORD"
